// sidebarsProjects.js (with dynamic sidebar generation)
module.exports = {
    projectsSidebar: [
      {
        type: 'autogenerated',
        dirName: '.',  // Automatically generates the sidebar for all .md files in the 'projects' folder
      },
    ],
  };
  