// sidebarsTimeline.js
module.exports = {
    timelineSidebar: [
      {
        type: 'autogenerated',
        dirName: '.',  // Automatically generates the sidebar for all .md files in the 'TimeLine' folder
      },
    ],
  };
    